import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { z } from 'zod';

// ============================================================================
// 1. Problem Details DTO (RFC 9457)
// ============================================================================

export class ProblemDetailsDto {
  @ApiProperty({
    example: 'https://errors.esma.example/gus/file-not-found',
    description: 'URI reference identifying the problem type',
  })
  type!: string;

  @ApiProperty({
    example: 'File not found',
    description: 'Short human-readable summary of problem',
  })
  title!: string;

  @ApiProperty({
    example: 404,
    description: 'HTTP status code generated by origin server',
  })
  status!: number;

  @ApiProperty({
    example: 'FILE_NOT_FOUND',
    description: 'Stable uppercase application error code',
  })
  code!: string;

  @ApiProperty({
    example: "File '0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b90' not found",
    description: 'Human-readable explanation specific to this occurrence',
  })
  detail!: string;

  @ApiProperty({
    example: '0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b91',
    description: 'Unique correlation ID for tracing and debugging',
  })
  correlationId!: string;

  @ApiPropertyOptional({
    example: [],
    description: 'Array of detailed sub-errors or field validation issues',
  })
  errors?: unknown[];
}

// ============================================================================
// 2. Route Parameter DTO
// ============================================================================

export const fileIdParamSchema = z.object({
  fileId: z.string().trim().min(1, 'fileId is required'),
});

export class FileIdParamDto {
  @ApiProperty({
    description: 'UUIDv7 unique identifier of the file',
    example: '0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b90',
  })
  fileId!: string;
}

// ============================================================================
// 3. File Upload DTO & Schemas
// ============================================================================

export const fileUploadMetadataSchema = z.object({
  folder: z.string().trim().optional(),
  visibility: z.enum(['public', 'tenant', 'private']).optional(),
  tags: z
    .union([z.array(z.string()), z.string()])
    .optional()
    .transform((val) => {
      if (!val) return undefined;
      if (Array.isArray(val)) return val;
      if (typeof val === 'string') {
        try {
          const parsed: unknown = JSON.parse(val);
          return Array.isArray(parsed) ? parsed.map(String) : [val];
        } catch {
          return val
            .split(',')
            .map((s) => s.trim())
            .filter(Boolean);
        }
      }
      return undefined;
    }),
  attributes: z
    .union([z.record(z.string(), z.unknown()), z.string()])
    .optional()
    .transform((val) => {
      if (!val) return undefined;
      if (typeof val === 'object' && !Array.isArray(val)) {
        const out: Record<string, string> = {};
        for (const [k, v] of Object.entries(val)) {
          out[k] = String(v);
        }
        return out;
      }
      if (typeof val === 'string') {
        try {
          const parsed: unknown = JSON.parse(val);
          if (
            typeof parsed === 'object' &&
            parsed !== null &&
            !Array.isArray(parsed)
          ) {
            const out: Record<string, string> = {};
            for (const [k, v] of Object.entries(
              parsed as Record<string, unknown>,
            )) {
              out[k] = String(v);
            }
            return out;
          }
        } catch {
          // ignore invalid json string
        }
      }
      return undefined;
    }),
  subTenantId: z.string().trim().optional(),
  atomic: z
    .union([z.boolean(), z.string()])
    .optional()
    .transform((val) => {
      if (typeof val === 'boolean') return val;
      if (val === 'true' || val === '1') return true;
      if (val === 'false' || val === '0') return false;
      return undefined;
    }),
});

export class FileUploadBodyDto {
  @ApiProperty({
    type: 'string',
    format: 'binary',
    description: 'File payload(s) to upload',
  })
  file!: unknown;

  @ApiPropertyOptional({
    description: 'Target logical folder path',
    example: 'reports/2026',
  })
  folder?: string;

  @ApiPropertyOptional({
    enum: ['public', 'tenant', 'private'],
    default: 'tenant',
    description: 'File visibility level',
  })
  visibility?: 'public' | 'tenant' | 'private';

  @ApiPropertyOptional({
    description: 'Comma-separated tags or JSON array of strings',
    example: 'finance,academic,q1',
  })
  tags?: string[] | string;

  @ApiPropertyOptional({
    description: 'Key-value metadata dictionary (JSON string or object)',
    example: '{"department":"admissions"}',
  })
  attributes?: Record<string, string> | string;

  @ApiPropertyOptional({
    description: 'Sub-tenant (branch) ID to scope the uploaded file',
    example: 'branch_abj_01',
  })
  subTenantId?: string;
}

// ============================================================================
// 4. File Manifest Response DTO (ARCH §9.2)
// ============================================================================

export class ReplicaStatusDto {
  @ApiProperty({
    enum: [
      'QUEUED',
      'AVAILABLE',
      'FAILED',
      'DELETING',
      'DELETED',
      'SKIPPED_BY_POLICY',
    ],
    example: 'AVAILABLE',
  })
  status!: string;

  @ApiPropertyOptional({
    example: '2026-09-21T12:00:00.120Z',
    nullable: true,
  })
  syncedAt?: string | null;
}

export class ManifestDataDto {
  @ApiProperty({ example: '0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b90' })
  fileId!: string;

  @ApiProperty({ example: 'academic_report_2026.pdf' })
  filename!: string;

  @ApiProperty({ example: 'application/pdf' })
  mimetype!: string;

  @ApiProperty({ example: 2458902 })
  size!: number;

  @ApiPropertyOptional({
    example: '9f2b5c0a1d7e4b6a8c3f0e1d2a4b6c8e0f1a3b5c7d9e1f2a4b6c8d0e2f4a6b8c',
    nullable: true,
  })
  sha256?: string | null;

  @ApiProperty({
    enum: ['public', 'tenant', 'subtenant', 'private'],
    example: 'tenant',
  })
  visibility!: string;

  @ApiProperty({
    example:
      'https://upload.esma.example/api/v1/files/0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b90',
  })
  canonicalUrl!: string;

  @ApiPropertyOptional({ example: null, nullable: true })
  publicUrl?: string | null;

  @ApiProperty({ example: 'seaweedfs' })
  primaryProvider!: string;

  @ApiProperty({
    description: 'Map of storage providers to replica sync status',
    example: {
      seaweedfs: { status: 'AVAILABLE', syncedAt: '2026-09-21T12:00:00.120Z' },
      local: { status: 'QUEUED', syncedAt: null },
    },
  })
  replicas!: Record<string, ReplicaStatusDto>;

  @ApiProperty({
    enum: ['QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED'],
    example: 'QUEUED',
  })
  replicationStatus!: string;

  @ApiProperty({ example: 'NOT_REQUIRED' })
  scanStatus!: string;

  @ApiProperty({ example: '2026-09-21T12:00:00.125Z' })
  createdAt!: string;
}

export class FileManifestResponseDto {
  @ApiProperty({ example: true })
  success!: boolean;

  @ApiPropertyOptional({
    example: 'File uploaded. Replication to secondary storage is queued.',
  })
  message?: string;

  @ApiProperty({ type: ManifestDataDto })
  data!: ManifestDataDto;
}

export class FileUploadSuccessResponseDto {
  @ApiProperty({ example: true })
  success!: boolean;

  @ApiProperty({
    example: 'File uploaded. Replication to secondary storage is queued.',
  })
  message!: string;

  @ApiProperty({
    description: 'File manifest or array of manifests for batch upload',
    oneOf: [
      { $ref: '#/components/schemas/ManifestDataDto' },
      {
        type: 'array',
        items: { $ref: '#/components/schemas/ManifestDataDto' },
      },
    ],
  })
  data!: ManifestDataDto | ManifestDataDto[];
}

export class FileUploadMultiStatusItemDto {
  @ApiProperty({ example: true })
  success!: boolean;

  @ApiPropertyOptional({ example: '0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b90' })
  fileId?: string;

  @ApiPropertyOptional({ type: ManifestDataDto })
  manifest?: ManifestDataDto;

  @ApiPropertyOptional({ example: 'report.pdf' })
  filename?: string;

  @ApiPropertyOptional({
    description: 'Error information if file ingestion failed',
    example: { code: 'UNSUPPORTED_MEDIA_TYPE', message: 'MIME not allowed' },
  })
  error?: unknown;
}

export class FileUploadMultiStatusResponseDto {
  @ApiProperty({ example: false })
  success!: boolean;

  @ApiProperty({ example: 'Batch upload completed with one or more failures.' })
  message!: string;

  @ApiProperty({ type: [FileUploadMultiStatusItemDto] })
  outcomes!: FileUploadMultiStatusItemDto[];
}

// ============================================================================
// 5. Query Filters DTO & Schemas (GET /api/v1/files)
// ============================================================================

export const fileListQuerySchema = z.object({
  folder: z.string().trim().optional(),
  subTenantId: z.string().trim().optional(),
  mimetype: z.string().trim().optional(),
  tag: z.string().trim().optional(),
  createdFrom: z.string().trim().optional(),
  createdTo: z.string().trim().optional(),
  cursor: z.string().trim().optional(),
  limit: z
    .union([z.string(), z.number()])
    .optional()
    .transform((val) => {
      if (val === undefined || val === '') return 20;
      const n = typeof val === 'number' ? val : parseInt(val, 10);
      if (isNaN(n) || n < 1) return 20;
      if (n > 100) return 100;
      return n;
    }),
});

export class FileListQueryDto {
  @ApiPropertyOptional({
    description: 'Filter files by logical folder prefix',
    example: 'admissions/2026',
  })
  folder?: string;

  @ApiPropertyOptional({
    description: 'Filter files by sub-tenant (branch) ID',
    example: 'branch_abj_01',
  })
  subTenantId?: string;

  @ApiPropertyOptional({
    description: 'Filter files by MIME type',
    example: 'application/pdf',
  })
  mimetype?: string;

  @ApiPropertyOptional({
    description: 'Filter files by tag',
    example: 'financial',
  })
  tag?: string;

  @ApiPropertyOptional({
    description: 'Filter files created after ISO timestamp',
    example: '2026-01-01T00:00:00Z',
  })
  createdFrom?: string;

  @ApiPropertyOptional({
    description: 'Filter files created before ISO timestamp',
    example: '2026-12-31T23:59:59Z',
  })
  createdTo?: string;

  @ApiPropertyOptional({
    description: 'Opaque pagination cursor from previous response',
  })
  cursor?: string;

  @ApiPropertyOptional({
    description: 'Page limit (1 to 100, default 20)',
    example: 20,
    default: 20,
  })
  limit?: number;
}

export class FileListResponseDto {
  @ApiProperty({ type: [ManifestDataDto] })
  files!: ManifestDataDto[];

  @ApiPropertyOptional({ example: 'cursor_eyJpZCI6IjAxOThm...' })
  nextCursor?: string | null;

  @ApiProperty({ example: 1 })
  count!: number;
}

// ============================================================================
// 6. Content Read Query DTO (GET /api/v1/files/:fileId)
// ============================================================================

export const fileReadQuerySchema = z.object({
  exp: z.string().trim().optional(),
  disp: z.enum(['inline', 'attachment']).optional(),
  sig: z.string().trim().optional(),
  redirect: z.enum(['auto', 'always', 'never']).optional(),
  provider: z.enum(['local', 'cloudinary', 'seaweedfs']).optional(),
  variant: z.string().trim().optional(),
});

export class FileReadQueryDto {
  @ApiPropertyOptional({
    description: 'Expiry epoch timestamp for signed URL authentication',
  })
  exp?: string;

  @ApiPropertyOptional({
    enum: ['inline', 'attachment'],
    description: 'Override Content-Disposition header',
  })
  disp?: 'inline' | 'attachment';

  @ApiPropertyOptional({
    description: 'HMAC signature for signed URL authentication',
  })
  sig?: string;

  @ApiPropertyOptional({
    enum: ['auto', 'always', 'never'],
    default: 'auto',
    description:
      'Redirect behavior for storage driver URL vs streaming through API',
  })
  redirect?: 'auto' | 'always' | 'never';

  @ApiPropertyOptional({
    enum: ['local', 'cloudinary', 'seaweedfs'],
    description: 'Specific replica provider to read from (admin only)',
  })
  provider?: 'local' | 'cloudinary' | 'seaweedfs';

  @ApiPropertyOptional({
    description: 'Image derivative variant name (e.g. thumb, medium)',
    example: 'thumb',
  })
  variant?: string;
}

// ============================================================================
// 7. Signed URL DTO & Schemas (POST /api/v1/files/:fileId/signed-url)
// ============================================================================

export const createSignedUrlSchema = z.object({
  expiresInSeconds: z.number().int().min(1).max(604800).optional(),
  ttlSeconds: z.number().int().min(1).max(604800).optional(),
  disposition: z.enum(['inline', 'attachment']).optional(),
});

export class CreateSignedUrlDto {
  @ApiPropertyOptional({
    description:
      'Lifetime of signed URL in seconds (max 7 days = 604800s, default 900s)',
    example: 3600,
    default: 900,
  })
  expiresInSeconds?: number;

  @ApiPropertyOptional({
    description: 'Alias for expiresInSeconds (ARCH §9.1)',
    example: 3600,
  })
  ttlSeconds?: number;

  @ApiPropertyOptional({
    enum: ['inline', 'attachment'],
    description: 'Content-Disposition when accessing via signed URL',
    default: 'attachment',
  })
  disposition?: 'inline' | 'attachment';
}

export class SignedUrlResponseDto {
  @ApiProperty({ example: '0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b90' })
  fileId!: string;

  @ApiProperty({
    example:
      'https://upload.esma.example/api/v1/files/0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b90?exp=1790683200&disp=attachment&sig=a8c1f9...',
  })
  url!: string;

  @ApiProperty({ example: '2026-09-28T12:00:00.000Z' })
  expiresAt!: string;

  @ApiPropertyOptional({
    enum: ['inline', 'attachment'],
    example: 'attachment',
  })
  disposition?: 'inline' | 'attachment';
}

// ============================================================================
// 8. Bulk Delete DTO & Schemas (POST /api/v1/files/bulk-delete)
// ============================================================================

export const bulkDeleteSchema = z.object({
  fileIds: z
    .array(z.string().trim().min(1, 'fileId cannot be empty'))
    .min(1, 'At least 1 fileId is required')
    .max(100, 'Cannot delete more than 100 files at once'),
});

export class BulkDeleteRequestDto {
  @ApiProperty({
    description: 'Array of file IDs to delete (1 to 100)',
    example: [
      '0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b90',
      '0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b91',
    ],
  })
  fileIds!: string[];
}

export class BulkDeleteResultItemDto {
  @ApiProperty({ example: '0198f3a2-7c1e-7b40-9d2a-5e6f1a8c3b90' })
  id!: string;

  @ApiProperty({ example: true })
  deleted!: boolean;

  @ApiPropertyOptional({ example: 'File not found' })
  error?: string;
}

export class BulkDeleteResponseDto {
  @ApiProperty({ example: 2 })
  requested!: number;

  @ApiProperty({ example: 2 })
  deletedCount!: number;

  @ApiProperty({ example: 0 })
  failedCount!: number;

  @ApiProperty({ type: [BulkDeleteResultItemDto] })
  results!: BulkDeleteResultItemDto[];
}
